### ISSUE TITLE
ghostwriter/collection composer config misconfigured

### ISSUE THREAD

**Issue by kwilliams1987** [ghostwriter/collection#14]
`ghostwriter/collection` isn't compatible with `ghostwriter/option` v1.5.0+ but also doesn't clamp the dependency correctly.

The cleanup of `ghostwriter/option` in release 1.5.0 changed the namespaces of interfaces.

`ghostwriter/collection` requires `ghostwriter/option:^1.4` which can cause it to download 1.5.0 in new instances/upgrades.

Either the `composer.json` for `ghostwriter/collection` needs to be updated to require  `ghostwriter/option:1.4.*` or  `ghostwriter/collection` should be updated to match v1.5.0 and changed to require  `ghostwriter/option:^1.5`

Forcing the `ghostwriter/option` version back to 1.4 with an explicit `composer require "ghostwriter/option:1.4.*"` resolves the issue temporarily.

**Comment by ghostwriter** [comment]
Hi @kwilliams1987,

Thanks for catching this regression and providing a detailed report.

- [x] Bump the `ghostwriter/option` to `^1.5`
- [x] Correct the namespace change
- [ ] Tag a release.

Thanks again for your contribution!
